{{ if not .Values.admin_token_existingSecret }}
{{ if not .Values.admin_token_existingSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "theo-client.fullname" . }}-admin-token"
  labels:
    app.kubernetes.io/name: {{ include "theo-client.name" . }}
    helm.sh/chart: {{ include "theo-client.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  admin_token:  {{ .Values.admin_token | b64enc }}
{{ end }}
{{ end }}
