{{ if not .Values.client_token_existingSecret }}
{{ if not .Values.client_token_existingSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "theo-client.fullname" . }}-client-tokens"
  labels:
    app.kubernetes.io/name: {{ include "theo-client.name" . }}
    helm.sh/chart: {{ include "theo-client.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  client_token:  {{ .Values.client_token | b64enc }}
{{ end }}
{{ end }}
