{{ if not .Values.admin_token_existingSecret }}
{{ if not .Values.admin_token_existingSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "theo.fullname" . }}-admin-token"
  labels:
    app.kubernetes.io/name: {{ include "theo.name" . }}
    helm.sh/chart: {{ include "theo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.admin_token }}
  admin_token:  {{ .Values.admin_token | b64enc }}
  {{ else }}
  admin_token: {{ randAlphaNum 20 | b64enc }}
  {{ end }}
{{ end }}
{{ end }}
