{{ if not .Values.db_password_existingSecret }}
{{ if not .Values.db_password_existingSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "theo.fullname" . }}-db-password"
  labels:
    app.kubernetes.io/name: {{ include "theo.name" . }}
    helm.sh/chart: {{ include "theo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  db_password:  {{ .Values.db_password | b64enc }}
{{ end }}
{{ end }}
