---
name: ci

# yamllint disable-line rule:truthy
on: push

jobs:
  ci:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint YAML files
        uses: karancode/yamllint-github-action@master

      - name: Lint Markdown files
        uses: actionshub/markdownlint@v1.0.0

      - name: Lint Charts
        uses: helm/chart-testing-action@v2.1.0
        with:
          command: lint --all --debug
